version: '3.8'
services:
  app:
    image: ${APP_IMAGE:-ghcr.io/amrhas82/addypin:latest}
    ports:
      - "127.0.0.1:3000:3000"  # Production
      # - "127.0.0.1:8080:3000"  # Staging (use different compose file for staging)
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://addypin_user:${DB_PASSWORD}@172.17.0.1:5432/addypin?sslmode=require
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

# No postgres service definition - using native PostgreSQL
# No volumes or networks section needed for single service
